apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vault-operator
  name: vault-operator-vaultserver-admin-role
rules:
- apiGroups:
  - vault-operator.io
  resources:
  - vaultservers
  verbs:
  - '*'
- apiGroups:
  - vault-operator.io
  resources:
  - vaultservers/status
  verbs:
  - get
