apiVersion: vault-operator.io/v1alpha1
kind: VaultServer
metadata:
  labels:
    app.kubernetes.io/name: vault-operator
    app.kubernetes.io/managed-by: kustomize
  name: vaultserver-sample
spec:
  config: 
    ui: True
    clusterName: Coucou
    cacheSize: 4242
    experiments: ["events.alpha1", "secrets.import.alpha1"]
    defaultLeaseTTL: 2h7m5s
    listenerTcp:
      tls:
        disable: false
      httpTimeout:
        read: 10s
      xForwardedFor:
        rejectNotPresent: true
      proxyProcotol:
        behavior: use_always
        authorizedAddrs:
          - 127.0.0.1
          - 127.0.0.1
      telemetry:
        unauthenticatedMetricsAccess: true
      profiling:
        unauthenticatedPprofAccess: true
      customResponseHeaders:
        default:
          CoucouDefault: 
          - "CoucouDefaultVal"
          CoucouDefault2: 
          - "CoucouDefault2Val"
        "4xx": 
          CoucouDefault: 
          - "CoucouDefaultVal"
          CoucouDefault2: 
          - "CoucouDefault2Val"
        "202":
          CoucouDefault: 
          - "CoucouDefaultVal"
          CoucouDefault2: 
          - "CoucouDefault2Val"
        "2xx": 
          CoucouDefault: 
          - "CoucouDefaultVal"
          CoucouDefault2: 
          - "CoucouDefault2Val"
        "3xx":
          CoucouDefault: 
          - "CoucouDefaultVal"
          CoucouDefault2:
          - "CoucouDefault2Val"
    # storage:
    #   ociObjectStorage:
    #     region: coucou
    #     bucketName: bucket
    #     namespaceName: dd
    #     haEnabled: true
    #     lockBucketName: lol
    storage:
      raft:
        retryJoin:
        - autoJoinScheme: https
          leaderApiAddr: 127.0.0.1:8200
  image: ""
  size: 1