apiVersion: vault-operator.io/v1alpha1
kind: VaultServer
metadata:
  labels:
    app.kubernetes.io/name: vault-operator
    app.kubernetes.io/managed-by: kustomize
  name: vaultserver-sample
spec:
  # TODO(user): Add fields here
