//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSKmsSealSpec) DeepCopyInto(out *AWSKmsSealSpec) {
	*out = *in
	out.InternalSealSpec = in.InternalSealSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSKmsSealSpec.
func (in *AWSKmsSealSpec) DeepCopy() *AWSKmsSealSpec {
	if in == nil {
		return nil
	}
	out := new(AWSKmsSealSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdaptiveOverloadProtectionSpec) DeepCopyInto(out *AdaptiveOverloadProtectionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdaptiveOverloadProtectionSpec.
func (in *AdaptiveOverloadProtectionSpec) DeepCopy() *AdaptiveOverloadProtectionSpec {
	if in == nil {
		return nil
	}
	out := new(AdaptiveOverloadProtectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AliCloudKMSSealSpec) DeepCopyInto(out *AliCloudKMSSealSpec) {
	*out = *in
	out.InternalSealSpec = in.InternalSealSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliCloudKMSSealSpec.
func (in *AliCloudKMSSealSpec) DeepCopy() *AliCloudKMSSealSpec {
	if in == nil {
		return nil
	}
	out := new(AliCloudKMSSealSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureKeyVaultSealSpec) DeepCopyInto(out *AzureKeyVaultSealSpec) {
	*out = *in
	out.InternalSealSpec = in.InternalSealSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureKeyVaultSealSpec.
func (in *AzureKeyVaultSealSpec) DeepCopy() *AzureKeyVaultSealSpec {
	if in == nil {
		return nil
	}
	out := new(AzureKeyVaultSealSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CirconusSpec) DeepCopyInto(out *CirconusSpec) {
	*out = *in
	out.Credentials = in.Credentials
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CirconusSpec.
func (in *CirconusSpec) DeepCopy() *CirconusSpec {
	if in == nil {
		return nil
	}
	out := new(CirconusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapKeySelector) DeepCopyInto(out *ConfigMapKeySelector) {
	*out = *in
	out.ConfigMapRef = in.ConfigMapRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapKeySelector.
func (in *ConfigMapKeySelector) DeepCopy() *ConfigMapKeySelector {
	if in == nil {
		return nil
	}
	out := new(ConfigMapKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapSelector) DeepCopyInto(out *ConfigMapSelector) {
	*out = *in
	out.ConfigMapRef = in.ConfigMapRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapSelector.
func (in *ConfigMapSelector) DeepCopy() *ConfigMapSelector {
	if in == nil {
		return nil
	}
	out := new(ConfigMapSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsulSpec) DeepCopyInto(out *ConsulSpec) {
	*out = *in
	if in.ServiceTags != nil {
		in, out := &in.ServiceTags, &out.ServiceTags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ServiceMeta != nil {
		in, out := &in.ServiceMeta, &out.ServiceMeta
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.Token = in.Token
	out.Tls = in.Tls
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsulSpec.
func (in *ConsulSpec) DeepCopy() *ConsulSpec {
	if in == nil {
		return nil
	}
	out := new(ConsulSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsulTlsSpec) DeepCopyInto(out *ConsulTlsSpec) {
	*out = *in
	out.CaCert = in.CaCert
	out.ClientCert = in.ClientCert
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsulTlsSpec.
func (in *ConsulTlsSpec) DeepCopy() *ConsulTlsSpec {
	if in == nil {
		return nil
	}
	out := new(ConsulTlsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CorsSpec) DeepCopyInto(out *CorsSpec) {
	*out = *in
	if in.AllowedOrigins != nil {
		in, out := &in.AllowedOrigins, &out.AllowedOrigins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedHeaders != nil {
		in, out := &in.AllowedHeaders, &out.AllowedHeaders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CorsSpec.
func (in *CorsSpec) DeepCopy() *CorsSpec {
	if in == nil {
		return nil
	}
	out := new(CorsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomMaxJsonSpec) DeepCopyInto(out *CustomMaxJsonSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomMaxJsonSpec.
func (in *CustomMaxJsonSpec) DeepCopy() *CustomMaxJsonSpec {
	if in == nil {
		return nil
	}
	out := new(CustomMaxJsonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomResponseHeadersSpec) DeepCopyInto(out *CustomResponseHeadersSpec) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SpecificStatusCode != nil {
		in, out := &in.SpecificStatusCode, &out.SpecificStatusCode
		*out = make(map[SpecificStatusCodeSpec]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.CollectiveStatusCode != nil {
		in, out := &in.CollectiveStatusCode, &out.CollectiveStatusCode
		*out = make(map[CollectiveStatusCodeSpec]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomResponseHeadersSpec.
func (in *CustomResponseHeadersSpec) DeepCopy() *CustomResponseHeadersSpec {
	if in == nil {
		return nil
	}
	out := new(CustomResponseHeadersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataReference) DeepCopyInto(out *DataReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataReference.
func (in *DataReference) DeepCopy() *DataReference {
	if in == nil {
		return nil
	}
	out := new(DataReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatakeyReference) DeepCopyInto(out *DatakeyReference) {
	*out = *in
	out.DataReference = in.DataReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatakeyReference.
func (in *DatakeyReference) DeepCopy() *DatakeyReference {
	if in == nil {
		return nil
	}
	out := new(DatakeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DogStatsDSpec) DeepCopyInto(out *DogStatsDSpec) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DogStatsDSpec.
func (in *DogStatsDSpec) DeepCopy() *DogStatsDSpec {
	if in == nil {
		return nil
	}
	out := new(DogStatsDSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GcpKmsSealSpec) DeepCopyInto(out *GcpKmsSealSpec) {
	*out = *in
	out.InternalSealSpec = in.InternalSealSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GcpKmsSealSpec.
func (in *GcpKmsSealSpec) DeepCopy() *GcpKmsSealSpec {
	if in == nil {
		return nil
	}
	out := new(GcpKmsSealSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPTimeoutSpec) DeepCopyInto(out *HTTPTimeoutSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPTimeoutSpec.
func (in *HTTPTimeoutSpec) DeepCopy() *HTTPTimeoutSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPTimeoutSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalSealSpec) DeepCopyInto(out *InternalSealSpec) {
	*out = *in
	out.Credentials = in.Credentials
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalSealSpec.
func (in *InternalSealSpec) DeepCopy() *InternalSealSpec {
	if in == nil {
		return nil
	}
	out := new(InternalSealSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalStorageSpec) DeepCopyInto(out *InternalStorageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalStorageSpec.
func (in *InternalStorageSpec) DeepCopy() *InternalStorageSpec {
	if in == nil {
		return nil
	}
	out := new(InternalStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalUserLockoutSpec) DeepCopyInto(out *InternalUserLockoutSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalUserLockoutSpec.
func (in *InternalUserLockoutSpec) DeepCopy() *InternalUserLockoutSpec {
	if in == nil {
		return nil
	}
	out := new(InternalUserLockoutSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmsLibrarySpec) DeepCopyInto(out *KmsLibrarySpec) {
	*out = *in
	in.Library.DeepCopyInto(&out.Library)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmsLibrarySpec.
func (in *KmsLibrarySpec) DeepCopy() *KmsLibrarySpec {
	if in == nil {
		return nil
	}
	out := new(KmsLibrarySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenerSpec) DeepCopyInto(out *ListenerSpec) {
	*out = *in
	in.MaxRequestLimit.DeepCopyInto(&out.MaxRequestLimit)
	out.TLS = in.TLS
	out.HTTPimeout = in.HTTPimeout
	in.ProxyProtocol.DeepCopyInto(&out.ProxyProtocol)
	in.XForwarded.DeepCopyInto(&out.XForwarded)
	in.Cors.DeepCopyInto(&out.Cors)
	in.CustomResponseHeaders.DeepCopyInto(&out.CustomResponseHeaders)
	out.Redact = in.Redact
	out.CustomMaxJson = in.CustomMaxJson
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerSpec.
func (in *ListenerSpec) DeepCopy() *ListenerSpec {
	if in == nil {
		return nil
	}
	out := new(ListenerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenerTlsSpec) DeepCopyInto(out *ListenerTlsSpec) {
	*out = *in
	out.Cert = in.Cert
	out.ClientCa = in.ClientCa
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerTlsSpec.
func (in *ListenerTlsSpec) DeepCopy() *ListenerTlsSpec {
	if in == nil {
		return nil
	}
	out := new(ListenerTlsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaxRequestLimitSpec) DeepCopyInto(out *MaxRequestLimitSpec) {
	*out = *in
	out.Size = in.Size.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaxRequestLimitSpec.
func (in *MaxRequestLimitSpec) DeepCopy() *MaxRequestLimitSpec {
	if in == nil {
		return nil
	}
	out := new(MaxRequestLimitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIKmsSealSpec) DeepCopyInto(out *OCIKmsSealSpec) {
	*out = *in
	out.InternalSealSpec = in.InternalSealSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIKmsSealSpec.
func (in *OCIKmsSealSpec) DeepCopy() *OCIKmsSealSpec {
	if in == nil {
		return nil
	}
	out := new(OCIKmsSealSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PKCS11SealSpec) DeepCopyInto(out *PKCS11SealSpec) {
	*out = *in
	out.Lib = in.Lib
	out.Pin = in.Pin
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PKCS11SealSpec.
func (in *PKCS11SealSpec) DeepCopy() *PKCS11SealSpec {
	if in == nil {
		return nil
	}
	out := new(PKCS11SealSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusSpec) DeepCopyInto(out *PrometheusSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusSpec.
func (in *PrometheusSpec) DeepCopy() *PrometheusSpec {
	if in == nil {
		return nil
	}
	out := new(PrometheusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyProtocolSpec) DeepCopyInto(out *ProxyProtocolSpec) {
	*out = *in
	if in.AuthorizedAddrs != nil {
		in, out := &in.AuthorizedAddrs, &out.AuthorizedAddrs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyProtocolSpec.
func (in *ProxyProtocolSpec) DeepCopy() *ProxyProtocolSpec {
	if in == nil {
		return nil
	}
	out := new(ProxyProtocolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedactSpec) DeepCopyInto(out *RedactSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedactSpec.
func (in *RedactSpec) DeepCopy() *RedactSpec {
	if in == nil {
		return nil
	}
	out := new(RedactSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationSpec) DeepCopyInto(out *ReplicationSpec) {
	*out = *in
	out.LogshipperBufferSize = in.LogshipperBufferSize.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationSpec.
func (in *ReplicationSpec) DeepCopy() *ReplicationSpec {
	if in == nil {
		return nil
	}
	out := new(ReplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReportingLicenseSpec) DeepCopyInto(out *ReportingLicenseSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReportingLicenseSpec.
func (in *ReportingLicenseSpec) DeepCopy() *ReportingLicenseSpec {
	if in == nil {
		return nil
	}
	out := new(ReportingLicenseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReportingSpec) DeepCopyInto(out *ReportingSpec) {
	*out = *in
	out.License = in.License
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReportingSpec.
func (in *ReportingSpec) DeepCopy() *ReportingSpec {
	if in == nil {
		return nil
	}
	out := new(ReportingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SealSpec) DeepCopyInto(out *SealSpec) {
	*out = *in
	out.AliCloudKMS = in.AliCloudKMS
	out.AWSKms = in.AWSKms
	out.AzureKeyVault = in.AzureKeyVault
	out.GCPKms = in.GCPKms
	out.OCIKms = in.OCIKms
	out.PKCS11 = in.PKCS11
	out.Transit = in.Transit
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SealSpec.
func (in *SealSpec) DeepCopy() *SealSpec {
	if in == nil {
		return nil
	}
	out := new(SealSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeySelector) DeepCopyInto(out *SecretKeySelector) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeySelector.
func (in *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(SecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretSelector) DeepCopyInto(out *SecretSelector) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretSelector.
func (in *SecretSelector) DeepCopy() *SecretSelector {
	if in == nil {
		return nil
	}
	out := new(SecretSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SentinelSpec) DeepCopyInto(out *SentinelSpec) {
	*out = *in
	if in.AdditionalEnabledModules != nil {
		in, out := &in.AdditionalEnabledModules, &out.AdditionalEnabledModules
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SentinelSpec.
func (in *SentinelSpec) DeepCopy() *SentinelSpec {
	if in == nil {
		return nil
	}
	out := new(SentinelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceRegistrationKubernetesSpec) DeepCopyInto(out *ServiceRegistrationKubernetesSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRegistrationKubernetesSpec.
func (in *ServiceRegistrationKubernetesSpec) DeepCopy() *ServiceRegistrationKubernetesSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceRegistrationKubernetesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceRegistrationSpec) DeepCopyInto(out *ServiceRegistrationSpec) {
	*out = *in
	in.Consul.DeepCopyInto(&out.Consul)
	out.Kubernetes = in.Kubernetes
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRegistrationSpec.
func (in *ServiceRegistrationSpec) DeepCopy() *ServiceRegistrationSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceRegistrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackDriverSpec) DeepCopyInto(out *StackDriverSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackDriverSpec.
func (in *StackDriverSpec) DeepCopy() *StackDriverSpec {
	if in == nil {
		return nil
	}
	out := new(StackDriverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatSiteSpec) DeepCopyInto(out *StatSiteSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatSiteSpec.
func (in *StatSiteSpec) DeepCopy() *StatSiteSpec {
	if in == nil {
		return nil
	}
	out := new(StatSiteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatsdSpec) DeepCopyInto(out *StatsdSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatsdSpec.
func (in *StatsdSpec) DeepCopy() *StatsdSpec {
	if in == nil {
		return nil
	}
	out := new(StatsdSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageAerospikeSpec) DeepCopyInto(out *StorageAerospikeSpec) {
	*out = *in
	if in.HostList != nil {
		in, out := &in.HostList, &out.HostList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Credentials = in.Credentials
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageAerospikeSpec.
func (in *StorageAerospikeSpec) DeepCopy() *StorageAerospikeSpec {
	if in == nil {
		return nil
	}
	out := new(StorageAerospikeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageAlicloudOssSpec) DeepCopyInto(out *StorageAlicloudOssSpec) {
	*out = *in
	out.InternalStorageSpec = in.InternalStorageSpec
	out.Credentials = in.Credentials
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageAlicloudOssSpec.
func (in *StorageAlicloudOssSpec) DeepCopy() *StorageAlicloudOssSpec {
	if in == nil {
		return nil
	}
	out := new(StorageAlicloudOssSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageAzureSpec) DeepCopyInto(out *StorageAzureSpec) {
	*out = *in
	out.InternalStorageSpec = in.InternalStorageSpec
	out.Credentials = in.Credentials
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageAzureSpec.
func (in *StorageAzureSpec) DeepCopy() *StorageAzureSpec {
	if in == nil {
		return nil
	}
	out := new(StorageAzureSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageCassandraSpec) DeepCopyInto(out *StorageCassandraSpec) {
	*out = *in
	out.InternalStorageSpec = in.InternalStorageSpec
	out.Credentials = in.Credentials
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageCassandraSpec.
func (in *StorageCassandraSpec) DeepCopy() *StorageCassandraSpec {
	if in == nil {
		return nil
	}
	out := new(StorageCassandraSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageCockroachDBSpec) DeepCopyInto(out *StorageCockroachDBSpec) {
	*out = *in
	out.InternalStorageSpec = in.InternalStorageSpec
	out.ConnectionUrl = in.ConnectionUrl
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageCockroachDBSpec.
func (in *StorageCockroachDBSpec) DeepCopy() *StorageCockroachDBSpec {
	if in == nil {
		return nil
	}
	out := new(StorageCockroachDBSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageConsulSpec) DeepCopyInto(out *StorageConsulSpec) {
	*out = *in
	out.InternalStorageSpec = in.InternalStorageSpec
	in.ConsulSpec.DeepCopyInto(&out.ConsulSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageConsulSpec.
func (in *StorageConsulSpec) DeepCopy() *StorageConsulSpec {
	if in == nil {
		return nil
	}
	out := new(StorageConsulSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageCouchDBSpec) DeepCopyInto(out *StorageCouchDBSpec) {
	*out = *in
	out.InternalStorageSpec = in.InternalStorageSpec
	out.Credentials = in.Credentials
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageCouchDBSpec.
func (in *StorageCouchDBSpec) DeepCopy() *StorageCouchDBSpec {
	if in == nil {
		return nil
	}
	out := new(StorageCouchDBSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageDynamoDBCapacitySpec) DeepCopyInto(out *StorageDynamoDBCapacitySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageDynamoDBCapacitySpec.
func (in *StorageDynamoDBCapacitySpec) DeepCopy() *StorageDynamoDBCapacitySpec {
	if in == nil {
		return nil
	}
	out := new(StorageDynamoDBCapacitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageDynamoDBSpec) DeepCopyInto(out *StorageDynamoDBSpec) {
	*out = *in
	out.Capacity = in.Capacity
	out.Credentials = in.Credentials
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageDynamoDBSpec.
func (in *StorageDynamoDBSpec) DeepCopy() *StorageDynamoDBSpec {
	if in == nil {
		return nil
	}
	out := new(StorageDynamoDBSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageEtcdMaxSpec) DeepCopyInto(out *StorageEtcdMaxSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageEtcdMaxSpec.
func (in *StorageEtcdMaxSpec) DeepCopy() *StorageEtcdMaxSpec {
	if in == nil {
		return nil
	}
	out := new(StorageEtcdMaxSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageEtcdSpec) DeepCopyInto(out *StorageEtcdSpec) {
	*out = *in
	out.Timeout = in.Timeout
	out.Max = in.Max
	out.Credentials = in.Credentials
	out.TLS = in.TLS
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageEtcdSpec.
func (in *StorageEtcdSpec) DeepCopy() *StorageEtcdSpec {
	if in == nil {
		return nil
	}
	out := new(StorageEtcdSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageEtcdTimeoutSpec) DeepCopyInto(out *StorageEtcdTimeoutSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageEtcdTimeoutSpec.
func (in *StorageEtcdTimeoutSpec) DeepCopy() *StorageEtcdTimeoutSpec {
	if in == nil {
		return nil
	}
	out := new(StorageEtcdTimeoutSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageFileSystemSpec) DeepCopyInto(out *StorageFileSystemSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageFileSystemSpec.
func (in *StorageFileSystemSpec) DeepCopy() *StorageFileSystemSpec {
	if in == nil {
		return nil
	}
	out := new(StorageFileSystemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageFoundationDbSpec) DeepCopyInto(out *StorageFoundationDbSpec) {
	*out = *in
	out.ClusterFile = in.ClusterFile
	out.Tls = in.Tls
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageFoundationDbSpec.
func (in *StorageFoundationDbSpec) DeepCopy() *StorageFoundationDbSpec {
	if in == nil {
		return nil
	}
	out := new(StorageFoundationDbSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageGoogleCloudSpannerSpec) DeepCopyInto(out *StorageGoogleCloudSpannerSpec) {
	*out = *in
	out.InternalStorageSpec = in.InternalStorageSpec
	out.Credentials = in.Credentials
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageGoogleCloudSpannerSpec.
func (in *StorageGoogleCloudSpannerSpec) DeepCopy() *StorageGoogleCloudSpannerSpec {
	if in == nil {
		return nil
	}
	out := new(StorageGoogleCloudSpannerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageGoogleCloudStorageSpec) DeepCopyInto(out *StorageGoogleCloudStorageSpec) {
	*out = *in
	out.InternalStorageSpec = in.InternalStorageSpec
	out.Credentials = in.Credentials
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageGoogleCloudStorageSpec.
func (in *StorageGoogleCloudStorageSpec) DeepCopy() *StorageGoogleCloudStorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageGoogleCloudStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageInMemSpec) DeepCopyInto(out *StorageInMemSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageInMemSpec.
func (in *StorageInMemSpec) DeepCopy() *StorageInMemSpec {
	if in == nil {
		return nil
	}
	out := new(StorageInMemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageMantaSpec) DeepCopyInto(out *StorageMantaSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageMantaSpec.
func (in *StorageMantaSpec) DeepCopy() *StorageMantaSpec {
	if in == nil {
		return nil
	}
	out := new(StorageMantaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageMsSqlSpec) DeepCopyInto(out *StorageMsSqlSpec) {
	*out = *in
	out.InternalStorageSpec = in.InternalStorageSpec
	out.Credentials = in.Credentials
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageMsSqlSpec.
func (in *StorageMsSqlSpec) DeepCopy() *StorageMsSqlSpec {
	if in == nil {
		return nil
	}
	out := new(StorageMsSqlSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageMySqlSpec) DeepCopyInto(out *StorageMySqlSpec) {
	*out = *in
	out.InternalStorageSpec = in.InternalStorageSpec
	out.Credentials = in.Credentials
	out.TlsCa = in.TlsCa
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageMySqlSpec.
func (in *StorageMySqlSpec) DeepCopy() *StorageMySqlSpec {
	if in == nil {
		return nil
	}
	out := new(StorageMySqlSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageOCIObjectStorageSpec) DeepCopyInto(out *StorageOCIObjectStorageSpec) {
	*out = *in
	out.Credentials = in.Credentials
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageOCIObjectStorageSpec.
func (in *StorageOCIObjectStorageSpec) DeepCopy() *StorageOCIObjectStorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageOCIObjectStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePostgreSqlAutModeSpec) DeepCopyInto(out *StoragePostgreSqlAutModeSpec) {
	*out = *in
	out.Aws = in.Aws
	out.Azure = in.Azure
	out.Gcp = in.Gcp
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePostgreSqlAutModeSpec.
func (in *StoragePostgreSqlAutModeSpec) DeepCopy() *StoragePostgreSqlAutModeSpec {
	if in == nil {
		return nil
	}
	out := new(StoragePostgreSqlAutModeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePostgreSqlAwsSpec) DeepCopyInto(out *StoragePostgreSqlAwsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePostgreSqlAwsSpec.
func (in *StoragePostgreSqlAwsSpec) DeepCopy() *StoragePostgreSqlAwsSpec {
	if in == nil {
		return nil
	}
	out := new(StoragePostgreSqlAwsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePostgreSqlAzureSpec) DeepCopyInto(out *StoragePostgreSqlAzureSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePostgreSqlAzureSpec.
func (in *StoragePostgreSqlAzureSpec) DeepCopy() *StoragePostgreSqlAzureSpec {
	if in == nil {
		return nil
	}
	out := new(StoragePostgreSqlAzureSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePostgreSqlGcpSpec) DeepCopyInto(out *StoragePostgreSqlGcpSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePostgreSqlGcpSpec.
func (in *StoragePostgreSqlGcpSpec) DeepCopy() *StoragePostgreSqlGcpSpec {
	if in == nil {
		return nil
	}
	out := new(StoragePostgreSqlGcpSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePostgreSqlSpec) DeepCopyInto(out *StoragePostgreSqlSpec) {
	*out = *in
	out.InternalStorageSpec = in.InternalStorageSpec
	out.ConnectionUrl = in.ConnectionUrl
	out.AuthMode = in.AuthMode
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePostgreSqlSpec.
func (in *StoragePostgreSqlSpec) DeepCopy() *StoragePostgreSqlSpec {
	if in == nil {
		return nil
	}
	out := new(StoragePostgreSqlSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageRaftRetrySpec) DeepCopyInto(out *StorageRaftRetrySpec) {
	*out = *in
	out.LeaderTls = in.LeaderTls
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageRaftRetrySpec.
func (in *StorageRaftRetrySpec) DeepCopy() *StorageRaftRetrySpec {
	if in == nil {
		return nil
	}
	out := new(StorageRaftRetrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageRaftSpec) DeepCopyInto(out *StorageRaftSpec) {
	*out = *in
	if in.RetryJoin != nil {
		in, out := &in.RetryJoin, &out.RetryJoin
		*out = make([]StorageRaftRetrySpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageRaftSpec.
func (in *StorageRaftSpec) DeepCopy() *StorageRaftSpec {
	if in == nil {
		return nil
	}
	out := new(StorageRaftSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageS3Spec) DeepCopyInto(out *StorageS3Spec) {
	*out = *in
	out.InternalStorageSpec = in.InternalStorageSpec
	out.Credentials = in.Credentials
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageS3Spec.
func (in *StorageS3Spec) DeepCopy() *StorageS3Spec {
	if in == nil {
		return nil
	}
	out := new(StorageS3Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	in.Aerospike.DeepCopyInto(&out.Aerospike)
	out.AlicloudOss = in.AlicloudOss
	out.InMem = in.InMem
	out.FileSystem = in.FileSystem
	out.Azure = in.Azure
	out.Cassandra = in.Cassandra
	out.CockroachDB = in.CockroachDB
	in.Consul.DeepCopyInto(&out.Consul)
	out.CouchDB = in.CouchDB
	out.DynamoDB = in.DynamoDB
	out.Etcd = in.Etcd
	out.FoundationDb = in.FoundationDb
	out.GoogleCloudSpanner = in.GoogleCloudSpanner
	out.GoogleCloudStorage = in.GoogleCloudStorage
	in.Raft.DeepCopyInto(&out.Raft)
	out.Manta = in.Manta
	out.MsSql = in.MsSql
	out.MySql = in.MySql
	out.OCIObjectStorage = in.OCIObjectStorage
	out.PostgreSql = in.PostgreSql
	out.S3 = in.S3
	out.Swift = in.Swift
	out.ZooKeeper = in.ZooKeeper
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSwiftDomainNameSpec) DeepCopyInto(out *StorageSwiftDomainNameSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSwiftDomainNameSpec.
func (in *StorageSwiftDomainNameSpec) DeepCopy() *StorageSwiftDomainNameSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSwiftDomainNameSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSwiftSpec) DeepCopyInto(out *StorageSwiftSpec) {
	*out = *in
	out.InternalStorageSpec = in.InternalStorageSpec
	out.Tenant = in.Tenant
	out.DomainName = in.DomainName
	out.Credentials = in.Credentials
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSwiftSpec.
func (in *StorageSwiftSpec) DeepCopy() *StorageSwiftSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSwiftSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSwiftTenantSpec) DeepCopyInto(out *StorageSwiftTenantSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSwiftTenantSpec.
func (in *StorageSwiftTenantSpec) DeepCopy() *StorageSwiftTenantSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSwiftTenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageZooKeeperSpec) DeepCopyInto(out *StorageZooKeeperSpec) {
	*out = *in
	out.AuthInfo = in.AuthInfo
	out.Tls = in.Tls
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageZooKeeperSpec.
func (in *StorageZooKeeperSpec) DeepCopy() *StorageZooKeeperSpec {
	if in == nil {
		return nil
	}
	out := new(StorageZooKeeperSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageZooKeeperTLSpec) DeepCopyInto(out *StorageZooKeeperTLSpec) {
	*out = *in
	out.Certificate = in.Certificate
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageZooKeeperTLSpec.
func (in *StorageZooKeeperTLSpec) DeepCopy() *StorageZooKeeperTLSpec {
	if in == nil {
		return nil
	}
	out := new(StorageZooKeeperTLSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetrySpec) DeepCopyInto(out *TelemetrySpec) {
	*out = *in
	if in.PrefixFilter != nil {
		in, out := &in.PrefixFilter, &out.PrefixFilter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Statsite = in.Statsite
	out.Statsd = in.Statsd
	out.Circonus = in.Circonus
	in.DogStatsD.DeepCopyInto(&out.DogStatsD)
	out.StackDriver = in.StackDriver
	out.Prometheus = in.Prometheus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetrySpec.
func (in *TelemetrySpec) DeepCopy() *TelemetrySpec {
	if in == nil {
		return nil
	}
	out := new(TelemetrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TlsTransitSpec) DeepCopyInto(out *TlsTransitSpec) {
	*out = *in
	out.CaCert = in.CaCert
	out.ClientCert = in.ClientCert
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TlsTransitSpec.
func (in *TlsTransitSpec) DeepCopy() *TlsTransitSpec {
	if in == nil {
		return nil
	}
	out := new(TlsTransitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransitSealSpec) DeepCopyInto(out *TransitSealSpec) {
	*out = *in
	out.InternalSealSpec = in.InternalSealSpec
	out.Tls = in.Tls
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransitSealSpec.
func (in *TransitSealSpec) DeepCopy() *TransitSealSpec {
	if in == nil {
		return nil
	}
	out := new(TransitSealSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserLockoutSpec) DeepCopyInto(out *UserLockoutSpec) {
	*out = *in
	out.All = in.All
	out.UserPass = in.UserPass
	out.LDAP = in.LDAP
	out.AppRole = in.AppRole
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserLockoutSpec.
func (in *UserLockoutSpec) DeepCopy() *UserLockoutSpec {
	if in == nil {
		return nil
	}
	out := new(UserLockoutSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultServer) DeepCopyInto(out *VaultServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultServer.
func (in *VaultServer) DeepCopy() *VaultServer {
	if in == nil {
		return nil
	}
	out := new(VaultServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultServerConfigSpec) DeepCopyInto(out *VaultServerConfigSpec) {
	*out = *in
	in.ClusterAddr.DeepCopyInto(&out.ClusterAddr)
	in.ApiAddr.DeepCopyInto(&out.ApiAddr)
	if in.Experiments != nil {
		in, out := &in.Experiments, &out.Experiments
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.License = in.License
	in.Listener.DeepCopyInto(&out.Listener)
	in.Telemetry.DeepCopyInto(&out.Telemetry)
	if in.UserLockout != nil {
		in, out := &in.UserLockout, &out.UserLockout
		*out = make([]UserLockoutSpec, len(*in))
		copy(*out, *in)
	}
	out.Seal = in.Seal
	in.ServiceRegistration.DeepCopyInto(&out.ServiceRegistration)
	in.Storage.DeepCopyInto(&out.Storage)
	in.KMSLibrary.DeepCopyInto(&out.KMSLibrary)
	in.Replication.DeepCopyInto(&out.Replication)
	out.Reporting = in.Reporting
	in.SentinelSpec.DeepCopyInto(&out.SentinelSpec)
	out.AdaptiveOverloadProtection = in.AdaptiveOverloadProtection
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultServerConfigSpec.
func (in *VaultServerConfigSpec) DeepCopy() *VaultServerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(VaultServerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultServerList) DeepCopyInto(out *VaultServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VaultServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultServerList.
func (in *VaultServerList) DeepCopy() *VaultServerList {
	if in == nil {
		return nil
	}
	out := new(VaultServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultServerSpec) DeepCopyInto(out *VaultServerSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultServerSpec.
func (in *VaultServerSpec) DeepCopy() *VaultServerSpec {
	if in == nil {
		return nil
	}
	out := new(VaultServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultServerStatus) DeepCopyInto(out *VaultServerStatus) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultServerStatus.
func (in *VaultServerStatus) DeepCopy() *VaultServerStatus {
	if in == nil {
		return nil
	}
	out := new(VaultServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XForwardedForSpec) DeepCopyInto(out *XForwardedForSpec) {
	*out = *in
	if in.ClientCertHeaderDecoders != nil {
		in, out := &in.ClientCertHeaderDecoders, &out.ClientCertHeaderDecoders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AuthorizedAddrs != nil {
		in, out := &in.AuthorizedAddrs, &out.AuthorizedAddrs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XForwardedForSpec.
func (in *XForwardedForSpec) DeepCopy() *XForwardedForSpec {
	if in == nil {
		return nil
	}
	out := new(XForwardedForSpec)
	in.DeepCopyInto(out)
	return out
}
